apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-staging-namespaces
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/saiello/sample-dry-argocd-cookiecutter.git
      revision: develop
      directories:
      - path: namespace-config/namespaces/*/staging
  template:
    metadata:
      name: '{{ path[2] }}-infra'
    spec:
      project: '{{ path[3] }}'
      source:
        repoURL: https://github.com/saiello/sample-dry-argocd-cookiecutter.git
        targetrevision: develop
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[2] }}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
