apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/quarkus-app

namePrefix: microservice-a-
commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/name: microservice-a
  foo: greet-app

images:
- name: image-name
  newName: docker.io/saiello/quarkus-greeting-api
  newTag: "latest"

configMapGenerator:
- envs:
  - application.env
  name: quarkus-app-envs