apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: greet-app
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/saiello/sample-dry-argocd-cookiecutter
      revision: HEAD
      directories:
      - path: overlays/production/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: greet-app
      source:
        repoURL: https://github.com/saiello/sample-dry-argocd-cookiecutter
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[1] }}'
      syncPolicy:
        automated:
            prune: true
