apiVersion: v1
kind: LimitRange
metadata:
  name: memory
spec:
  limits:
  - default:
      cpu: {{cookiecutter.default_limit_cpu}}
      memory: {{cookiecutter.default_limit_mem}}
    defaultRequest:
      cpu: {{cookiecutter.default_req_cpu}}
      memory: {{cookiecutter.default_req_mem}}
    max:
      memory: {{cookiecutter.memory_limit_max}}
    min:
      memory: {{cookiecutter.memory_limit_min}}
    type: Container